packages:
  - playground
catalogs:
  cli:
    '@antfu/eslint-config': ^4.15.0
    '@antfu/ni': ^25.0.0
    '@babel/parser': ^7.27.7
    '@babel/traverse': ^7.27.7
    '@vscode/vsce': ^3.5.0
    bumpp: ^10.2.0
    eslint: ^9.29.0
    esno: ^4.8.0
    lint-staged: ^16.1.2
    pnpm: ^10.12.1
    simple-git-hooks: ^2.13.0
    tsdown: ^0.12.8
    tsup: ^8.5.0
    typescript: ^5.8.3
    vite: ^6.3.5
    vitest: ^3.2.4
    vscode-ext-gen: ^1.0.2
  types:
    '@types/node': ^24.0.3
  utils:
    '@antfu/utils': ^9.2.0
    eslint-plugin-command: ^3.3.1
    ofetch: ^1.4.1
    reactive-vscode: ^0.3.0
    scule: ^1.3.0
onlyBuiltDependencies:
  - esbuild
