packages:
  - playground
catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^25.0.0
    '@babel/parser': ^7.28.0
    '@babel/traverse': ^7.28.0
    '@vscode/vsce': ^3.6.0
    bumpp: ^10.2.0
    eslint: ^9.30.1
    esno: ^4.8.0
    lint-staged: ^16.1.2
    pnpm: ^10.12.4
    simple-git-hooks: ^2.13.0
    tsdown: ^0.12.9
    typescript: ^5.8.3
    vite: ^7.0.2
    vitest: ^3.2.4
    vscode-ext-gen: ^1.1.0
  playground:
    vue: ^3.5.17
  types:
    '@types/eslint': ^9.6.1
    '@types/node': ^24.0.10
  utils:
    '@antfu/utils': ^9.2.0
    eslint-plugin-command: ^3.3.1
    local-pkg: ^1.1.1
    ofetch: ^1.4.1
    reactive-vscode: ^0.3.1
    scule: ^1.3.0
onlyBuiltDependencies:
  - esbuild
